name: Build
on:
  - push
  - pull_request

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 17.3.0
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn make
